In [1]:
import pandas as pd

In [6]:
df = pd.read_sas('/Users/tejaharshitamullapudi/Downloads/brfss-clinical-ai/data/raw/LLCP2024.XPT ', format='xport', encoding='utf-8')
print(df.shape)

(457670, 301)

In [7]:
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_LCSCTSN,_LCSPSTF,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK3,_RFDRHV9,_FLSHOT7,_PNEUMO3,_AIDTST4
0,1.0,2.0,02282024,02,28,2024,1100.0,2024000001,2.024000e+09,1.0,...,NaN,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,2.0,2.0
1,1.0,2.0,02212024,02,21,2024,1100.0,2024000002,2.024000e+09,1.0,...,4.0,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0
2,1.0,2.0,02212024,02,21,2024,1100.0,2024000003,2.024000e+09,1.0,...,4.0,2.0,1.0,1.000000e+02,2.0,1.400000e+03,1.0,NaN,NaN,2.0
3,1.0,2.0,02282024,02,28,2024,1100.0,2024000004,2.024000e+09,1.0,...,NaN,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0
4,1.0,2.0,02212024,02,21,2024,1100.0,2024000005,2.024000e+09,1.0,...,3.0,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,NaN,2.0

In [8]:
df['_STATE'].unique()

array([ 1.,  2.,  4.,  5.,  6.,  8.,  9., 10., 11., 12., 13., 15., 16.,
       17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29.,
       30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42.,
       44., 45., 46., 48., 49., 50., 51., 53., 54., 55., 56., 66., 72.,
       78.])

In [9]:
df.isnull().sum().sort_values(ascending=False).head(20)

RCSGEND1    457670
RCSXBRTH    457670
COLGHOUS    457656
CSRVCTL2    457088
ICFQSTVR    456931
CCLGHOUS    456244
HPVDSHT     455650
CSRVINST    455045
NOBCUSE8    454899
LASTSIG4    454443
CSRVCLIN    454128
CSRVDEIN    454126
CSRVINSR    454123
CSRVRTRN    454118
CSRVSUM     454114
CSRVDOC1    454108
HPVADSH1    454043
CASTHNO2    452865
NUMPHON4    452048
CSRVPAIN    451664
dtype: int64

In [11]:
df[['_STATE', 'DIABETE4', 'SMOKE100', 'CVDINFR4',]].head(10)

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

   _STATE  DIABETE4  SMOKE100  CVDINFR4
0     1.0       3.0       2.0       2.0
1     1.0       3.0       1.0       2.0
2     1.0       3.0       1.0       2.0
3     1.0       3.0       2.0       2.0
4     1.0       3.0       2.0       2.0
5     1.0       1.0       2.0       2.0
6     1.0       3.0       2.0       1.0
7     1.0       1.0       2.0       2.0
8     1.0       3.0       2.0       2.0
9     1.0       1.0       1.0       2.0